## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN","NAME"], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value=500
application_types_to_replace = application_df["APPLICATION_TYPE"].value_counts()[application_df["APPLICATION_TYPE"].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
value_counts = application_df["CLASSIFICATION"].value_counts()

# Filter the value counts to include only those with counts greater than 1
filtered_value_counts = value_counts[value_counts > 1]
filtered_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace= application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < 1800].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=["APPLICATION_TYPE", "CLASSIFICATION", "AFFILIATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT", "SPECIAL_CONSIDERATIONS"])
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=["IS_SUCCESSFUL"], axis=1)
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_feature = len(X_train.columns)
hidden_nodes_layer1= 100
hidden_nodes_layer2= 60
hidden_nodes_layer3= 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim= number_input_feature, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer2, activation='tanh'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer3, activation='swish'))

# Output layer
nn.add(tf.keras.layers.Dense(units= 1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               4400

 dense_1 (Dense)             (None, 60)                6060

 dense_2 (Dense)             (None, 30)                1830

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 12321 (48.13 KB)
Trainable params: 12321 (48.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer= "adam", metrics= ["accuracy"])

In [15]:
# Train the model
fit_model= nn.fit(X_train_scaled, y_train, epochs=250)

Epoch 1/250
804/804 [==============================] - 1s 858us/step - loss: 0.5660 - accuracy: 0.7236
Epoch 2/250
804/804 [==============================] - 1s 731us/step - loss: 0.5551 - accuracy: 0.7294
Epoch 3/250
804/804 [==============================] - 1s 723us/step - loss: 0.5518 - accuracy: 0.7296
Epoch 4/250
804/804 [==============================] - 1s 731us/step - loss: 0.5510 - accuracy: 0.7301
Epoch 5/250
804/804 [==============================] - 1s 728us/step - loss: 0.5492 - accuracy: 0.7311
Epoch 6/250
804/804 [==============================] - 1s 724us/step - loss: 0.5482 - accuracy: 0.7336
Epoch 7/250
804/804 [==============================] - 1s 726us/step - loss: 0.5476 - accuracy: 0.7319
Epoch 8/250
804/804 [==============================] - 1s 730us/step - loss: 0.5468 - accuracy: 0.7318
Epoch 9/250
804/804 [==============================] - 1s 730us/step - loss: 0.5463 - accuracy: 0.7334
Epoch 10/250
804/804 [==============================] - 1s 732us/step - loss: 0.5454 - accuracy: 0.7337
Epoch 11/250
804/804 [==============================] - 1s 738us/step - loss: 0.5448 - accuracy: 0.7337
Epoch 12/250
804/804 [==============================] - 1s 760us/step - loss: 0.5450 - accuracy: 0.7339
Epoch 13/250
804/804 [==============================] - 1s 732us/step - loss: 0.5441 - accuracy: 0.7345
Epoch 14/250
804/804 [==============================] - 1s 732us/step - loss: 0.5434 - accuracy: 0.7352
Epoch 15/250
804/804 [==============================] - 1s 731us/step - loss: 0.5433 - accuracy: 0.7342
Epoch 16/250
804/804 [==============================] - 1s 731us/step - loss: 0.5425 - accuracy: 0.7353
Epoch 17/250
804/804 [==============================] - 1s 745us/step - loss: 0.5421 - accuracy: 0.7356
Epoch 18/250
804/804 [==============================] - 1s 743us/step - loss: 0.5416 - accuracy: 0.7347
Epoch 19/250
804/804 [==============================] - 1s 759us/step - loss: 0.5415 - accuracy: 0.7346
Epoch 20/250
804/804 [==============================] - 1s 766us/step - loss: 0.5408 - accuracy: 0.7353
Epoch 21/250
804/804 [==============================] - 1s 745us/step - loss: 0.5409 - accuracy: 0.7357
Epoch 22/250
804/804 [==============================] - 1s 750us/step - loss: 0.5404 - accuracy: 0.7365
Epoch 23/250
804/804 [==============================] - 1s 735us/step - loss: 0.5403 - accuracy: 0.7368
Epoch 24/250
804/804 [==============================] - 1s 756us/step - loss: 0.5401 - accuracy: 0.7362
Epoch 25/250
804/804 [==============================] - 1s 752us/step - loss: 0.5400 - accuracy: 0.7365
Epoch 26/250
804/804 [==============================] - 1s 745us/step - loss: 0.5391 - accuracy: 0.7368
Epoch 27/250
804/804 [==============================] - 1s 748us/step - loss: 0.5395 - accuracy: 0.7375
Epoch 28/250
804/804 [==============================] - 1s 753us/step - loss: 0.5394 - accuracy: 0.7373
Epoch 29/250
804/804 [==============================] - 1s 768us/step - loss: 0.5388 - accuracy: 0.7374
Epoch 30/250
804/804 [==============================] - 1s 753us/step - loss: 0.5384 - accuracy: 0.7378
Epoch 31/250
804/804 [==============================] - 1s 754us/step - loss: 0.5383 - accuracy: 0.7381
Epoch 32/250
804/804 [==============================] - 1s 749us/step - loss: 0.5384 - accuracy: 0.7376
Epoch 33/250
804/804 [==============================] - 1s 739us/step - loss: 0.5378 - accuracy: 0.7363
Epoch 34/250
804/804 [==============================] - 1s 748us/step - loss: 0.5378 - accuracy: 0.7387
Epoch 35/250
804/804 [==============================] - 1s 757us/step - loss: 0.5376 - accuracy: 0.7385
Epoch 36/250
804/804 [==============================] - 1s 751us/step - loss: 0.5374 - accuracy: 0.7385
Epoch 37/250
804/804 [==============================] - 1s 748us/step - loss: 0.5371 - accuracy: 0.7397
Epoch 38/250
804/804 [==============================] - 1s 760us/step - loss: 0.5372 - accuracy: 0.7386
Epoch 39/250
804/804 [==============================] - 1s 749us/step - loss: 0.5368 - accuracy: 0.7384
Epoch 40/250
804/804 [==============================] - 1s 745us/step - loss: 0.5367 - accuracy: 0.7387
Epoch 41/250
804/804 [==============================] - 1s 747us/step - loss: 0.5363 - accuracy: 0.7389
Epoch 42/250
804/804 [==============================] - 1s 750us/step - loss: 0.5361 - accuracy: 0.7385
Epoch 43/250
804/804 [==============================] - 1s 754us/step - loss: 0.5364 - accuracy: 0.7380
Epoch 44/250
804/804 [==============================] - 1s 787us/step - loss: 0.5359 - accuracy: 0.7392
Epoch 45/250
804/804 [==============================] - 1s 749us/step - loss: 0.5357 - accuracy: 0.7389
Epoch 46/250
804/804 [==============================] - 1s 758us/step - loss: 0.5358 - accuracy: 0.7395
Epoch 47/250
804/804 [==============================] - 1s 746us/step - loss: 0.5355 - accuracy: 0.7388
Epoch 48/250
804/804 [==============================] - 1s 767us/step - loss: 0.5353 - accuracy: 0.7397
Epoch 49/250
804/804 [==============================] - 1s 751us/step - loss: 0.5352 - accuracy: 0.7397
Epoch 50/250
804/804 [==============================] - 1s 749us/step - loss: 0.5352 - accuracy: 0.7393
Epoch 51/250
804/804 [==============================] - 1s 765us/step - loss: 0.5351 - accuracy: 0.7394
Epoch 52/250
804/804 [==============================] - 1s 751us/step - loss: 0.5350 - accuracy: 0.7401
Epoch 53/250
804/804 [==============================] - 1s 753us/step - loss: 0.5352 - accuracy: 0.7396
Epoch 54/250
804/804 [==============================] - 1s 749us/step - loss: 0.5347 - accuracy: 0.7391
Epoch 55/250
804/804 [==============================] - 1s 754us/step - loss: 0.5348 - accuracy: 0.7399
Epoch 56/250
804/804 [==============================] - 1s 749us/step - loss: 0.5341 - accuracy: 0.7398
Epoch 57/250
804/804 [==============================] - 1s 766us/step - loss: 0.5344 - accuracy: 0.7403
Epoch 58/250
804/804 [==============================] - 1s 757us/step - loss: 0.5343 - accuracy: 0.7402
Epoch 59/250
804/804 [==============================] - 1s 745us/step - loss: 0.5343 - accuracy: 0.7406
Epoch 60/250
804/804 [==============================] - 1s 751us/step - loss: 0.5341 - accuracy: 0.7397
Epoch 61/250
804/804 [==============================] - 1s 745us/step - loss: 0.5344 - accuracy: 0.7400
Epoch 62/250
804/804 [==============================] - 1s 751us/step - loss: 0.5338 - accuracy: 0.7399
Epoch 63/250
804/804 [==============================] - 1s 755us/step - loss: 0.5337 - accuracy: 0.7399
Epoch 64/250
804/804 [==============================] - 1s 740us/step - loss: 0.5334 - accuracy: 0.7398
Epoch 65/250
804/804 [==============================] - 1s 739us/step - loss: 0.5337 - accuracy: 0.7401
Epoch 66/250
804/804 [==============================] - 1s 742us/step - loss: 0.5336 - accuracy: 0.7407
Epoch 67/250
804/804 [==============================] - 1s 760us/step - loss: 0.5334 - accuracy: 0.7402
Epoch 68/250
804/804 [==============================] - 1s 746us/step - loss: 0.5335 - accuracy: 0.7404
Epoch 69/250
804/804 [==============================] - 1s 746us/step - loss: 0.5335 - accuracy: 0.7403
Epoch 70/250
804/804 [==============================] - 1s 745us/step - loss: 0.5331 - accuracy: 0.7409
Epoch 71/250
804/804 [==============================] - 1s 739us/step - loss: 0.5328 - accuracy: 0.7403
Epoch 72/250
804/804 [==============================] - 1s 748us/step - loss: 0.5330 - accuracy: 0.7402
Epoch 73/250
804/804 [==============================] - 1s 744us/step - loss: 0.5329 - accuracy: 0.7401
Epoch 74/250
804/804 [==============================] - 1s 740us/step - loss: 0.5330 - accuracy: 0.7396
Epoch 75/250
804/804 [==============================] - 1s 744us/step - loss: 0.5331 - accuracy: 0.7399
Epoch 76/250
804/804 [==============================] - 1s 753us/step - loss: 0.5332 - accuracy: 0.7400
Epoch 77/250
804/804 [==============================] - 1s 754us/step - loss: 0.5329 - accuracy: 0.7404
Epoch 78/250
804/804 [==============================] - 1s 759us/step - loss: 0.5329 - accuracy: 0.7405
Epoch 79/250
804/804 [==============================] - 1s 744us/step - loss: 0.5330 - accuracy: 0.7407
Epoch 80/250
804/804 [==============================] - 1s 745us/step - loss: 0.5329 - accuracy: 0.7395
Epoch 81/250
804/804 [==============================] - 1s 744us/step - loss: 0.5325 - accuracy: 0.7406
Epoch 82/250
804/804 [==============================] - 1s 747us/step - loss: 0.5323 - accuracy: 0.7405
Epoch 83/250
804/804 [==============================] - 1s 746us/step - loss: 0.5326 - accuracy: 0.7402
Epoch 84/250
804/804 [==============================] - 1s 743us/step - loss: 0.5326 - accuracy: 0.7404
Epoch 85/250
804/804 [==============================] - 1s 758us/step - loss: 0.5327 - accuracy: 0.7403
Epoch 86/250
804/804 [==============================] - 1s 747us/step - loss: 0.5325 - accuracy: 0.7405
Epoch 87/250
804/804 [==============================] - 1s 753us/step - loss: 0.5323 - accuracy: 0.7404
Epoch 88/250
804/804 [==============================] - 1s 747us/step - loss: 0.5325 - accuracy: 0.7409
Epoch 89/250
804/804 [==============================] - 1s 747us/step - loss: 0.5329 - accuracy: 0.7409
Epoch 90/250
804/804 [==============================] - 1s 756us/step - loss: 0.5322 - accuracy: 0.7410
Epoch 91/250
804/804 [==============================] - 1s 747us/step - loss: 0.5319 - accuracy: 0.7402
Epoch 92/250
804/804 [==============================] - 1s 740us/step - loss: 0.5322 - accuracy: 0.7402
Epoch 93/250
804/804 [==============================] - 1s 744us/step - loss: 0.5323 - accuracy: 0.7404
Epoch 94/250
804/804 [==============================] - 1s 760us/step - loss: 0.5325 - accuracy: 0.7404
Epoch 95/250
804/804 [==============================] - 1s 743us/step - loss: 0.5319 - accuracy: 0.7412
Epoch 96/250
804/804 [==============================] - 1s 744us/step - loss: 0.5316 - accuracy: 0.7404
Epoch 97/250
804/804 [==============================] - 1s 745us/step - loss: 0.5317 - accuracy: 0.7409
Epoch 98/250
804/804 [==============================] - 1s 746us/step - loss: 0.5322 - accuracy: 0.7409
Epoch 99/250
804/804 [==============================] - 1s 748us/step - loss: 0.5322 - accuracy: 0.7405
Epoch 100/250
804/804 [==============================] - 1s 746us/step - loss: 0.5324 - accuracy: 0.7409
Epoch 101/250
804/804 [==============================] - 1s 755us/step - loss: 0.5318 - accuracy: 0.7411
Epoch 102/250
804/804 [==============================] - 1s 761us/step - loss: 0.5319 - accuracy: 0.7406
Epoch 103/250
804/804 [==============================] - 1s 752us/step - loss: 0.5322 - accuracy: 0.7408
Epoch 104/250
804/804 [==============================] - 1s 779us/step - loss: 0.5318 - accuracy: 0.7402
Epoch 105/250
804/804 [==============================] - 1s 744us/step - loss: 0.5318 - accuracy: 0.7403
Epoch 106/250
804/804 [==============================] - 1s 749us/step - loss: 0.5317 - accuracy: 0.7406
Epoch 107/250
804/804 [==============================] - 1s 743us/step - loss: 0.5317 - accuracy: 0.7414
Epoch 108/250
804/804 [==============================] - 1s 754us/step - loss: 0.5313 - accuracy: 0.7411
Epoch 109/250
804/804 [==============================] - 1s 747us/step - loss: 0.5320 - accuracy: 0.7415
Epoch 110/250
804/804 [==============================] - 1s 765us/step - loss: 0.5314 - accuracy: 0.7414
Epoch 111/250
804/804 [==============================] - 1s 749us/step - loss: 0.5315 - accuracy: 0.7416
Epoch 112/250
804/804 [==============================] - 1s 748us/step - loss: 0.5315 - accuracy: 0.7410
Epoch 113/250
804/804 [==============================] - 1s 759us/step - loss: 0.5313 - accuracy: 0.7407
Epoch 114/250
804/804 [==============================] - 1s 794us/step - loss: 0.5315 - accuracy: 0.7412
Epoch 115/250
804/804 [==============================] - 1s 749us/step - loss: 0.5317 - accuracy: 0.7411
Epoch 116/250
804/804 [==============================] - 1s 747us/step - loss: 0.5311 - accuracy: 0.7410
Epoch 117/250
804/804 [==============================] - 1s 748us/step - loss: 0.5313 - accuracy: 0.7405
Epoch 118/250
804/804 [==============================] - 1s 764us/step - loss: 0.5319 - accuracy: 0.7411
Epoch 119/250
804/804 [==============================] - 1s 747us/step - loss: 0.5318 - accuracy: 0.7410
Epoch 120/250
804/804 [==============================] - 1s 753us/step - loss: 0.5314 - accuracy: 0.7413
Epoch 121/250
804/804 [==============================] - 1s 747us/step - loss: 0.5315 - accuracy: 0.7411
Epoch 122/250
804/804 [==============================] - 1s 744us/step - loss: 0.5311 - accuracy: 0.7418
Epoch 123/250
804/804 [==============================] - 1s 751us/step - loss: 0.5309 - accuracy: 0.7415
Epoch 124/250
804/804 [==============================] - 1s 757us/step - loss: 0.5312 - accuracy: 0.7411
Epoch 125/250
804/804 [==============================] - 1s 749us/step - loss: 0.5309 - accuracy: 0.7410
Epoch 126/250
804/804 [==============================] - 1s 763us/step - loss: 0.5313 - accuracy: 0.7413
Epoch 127/250
804/804 [==============================] - 1s 745us/step - loss: 0.5312 - accuracy: 0.7413
Epoch 128/250
804/804 [==============================] - 1s 751us/step - loss: 0.5310 - accuracy: 0.7411
Epoch 129/250
804/804 [==============================] - 1s 751us/step - loss: 0.5313 - accuracy: 0.7411
Epoch 130/250
804/804 [==============================] - 1s 745us/step - loss: 0.5317 - accuracy: 0.7404
Epoch 131/250
804/804 [==============================] - 1s 747us/step - loss: 0.5311 - accuracy: 0.7413
Epoch 132/250
804/804 [==============================] - 1s 751us/step - loss: 0.5311 - accuracy: 0.7415
Epoch 133/250
804/804 [==============================] - 1s 760us/step - loss: 0.5308 - accuracy: 0.7416
Epoch 134/250
804/804 [==============================] - 1s 755us/step - loss: 0.5313 - accuracy: 0.7410
Epoch 135/250
804/804 [==============================] - 1s 793us/step - loss: 0.5312 - accuracy: 0.7407
Epoch 136/250
804/804 [==============================] - 1s 753us/step - loss: 0.5317 - accuracy: 0.7414
Epoch 137/250
804/804 [==============================] - 1s 744us/step - loss: 0.5310 - accuracy: 0.7414
Epoch 138/250
804/804 [==============================] - 1s 773us/step - loss: 0.5313 - accuracy: 0.7417
Epoch 139/250
804/804 [==============================] - 1s 744us/step - loss: 0.5312 - accuracy: 0.7409
Epoch 140/250
804/804 [==============================] - 1s 764us/step - loss: 0.5310 - accuracy: 0.7411
Epoch 141/250
804/804 [==============================] - 1s 745us/step - loss: 0.5310 - accuracy: 0.7417
Epoch 142/250
804/804 [==============================] - 1s 745us/step - loss: 0.5314 - accuracy: 0.7405
Epoch 143/250
804/804 [==============================] - 1s 754us/step - loss: 0.5316 - accuracy: 0.7406
Epoch 144/250
804/804 [==============================] - 1s 752us/step - loss: 0.5316 - accuracy: 0.7406
Epoch 145/250
804/804 [==============================] - 1s 748us/step - loss: 0.5309 - accuracy: 0.7411
Epoch 146/250
804/804 [==============================] - 1s 761us/step - loss: 0.5308 - accuracy: 0.7414
Epoch 147/250
804/804 [==============================] - 1s 749us/step - loss: 0.5309 - accuracy: 0.7418
Epoch 148/250
804/804 [==============================] - 1s 747us/step - loss: 0.5311 - accuracy: 0.7406
Epoch 149/250
804/804 [==============================] - 1s 750us/step - loss: 0.5310 - accuracy: 0.7415
Epoch 150/250
804/804 [==============================] - 1s 751us/step - loss: 0.5311 - accuracy: 0.7415
Epoch 151/250
804/804 [==============================] - 1s 761us/step - loss: 0.5308 - accuracy: 0.7411
Epoch 152/250
804/804 [==============================] - 1s 747us/step - loss: 0.5305 - accuracy: 0.7415
Epoch 153/250
804/804 [==============================] - 1s 764us/step - loss: 0.5314 - accuracy: 0.7407
Epoch 154/250
804/804 [==============================] - 1s 755us/step - loss: 0.5312 - accuracy: 0.7412
Epoch 155/250
804/804 [==============================] - 1s 751us/step - loss: 0.5306 - accuracy: 0.7409
Epoch 156/250
804/804 [==============================] - 1s 752us/step - loss: 0.5311 - accuracy: 0.7407
Epoch 157/250
804/804 [==============================] - 1s 750us/step - loss: 0.5310 - accuracy: 0.7408
Epoch 158/250
804/804 [==============================] - 1s 751us/step - loss: 0.5308 - accuracy: 0.7407
Epoch 159/250
804/804 [==============================] - 1s 759us/step - loss: 0.5307 - accuracy: 0.7413
Epoch 160/250
804/804 [==============================] - 1s 756us/step - loss: 0.5307 - accuracy: 0.7405
Epoch 161/250
804/804 [==============================] - 1s 749us/step - loss: 0.5310 - accuracy: 0.7414
Epoch 162/250
804/804 [==============================] - 1s 750us/step - loss: 0.5309 - accuracy: 0.7411
Epoch 163/250
804/804 [==============================] - 1s 752us/step - loss: 0.5307 - accuracy: 0.7408
Epoch 164/250
804/804 [==============================] - 1s 751us/step - loss: 0.5310 - accuracy: 0.7412
Epoch 165/250
804/804 [==============================] - 1s 746us/step - loss: 0.5308 - accuracy: 0.7404
Epoch 166/250
804/804 [==============================] - 1s 763us/step - loss: 0.5314 - accuracy: 0.7403
Epoch 167/250
804/804 [==============================] - 1s 752us/step - loss: 0.5313 - accuracy: 0.7412
Epoch 168/250
804/804 [==============================] - 1s 761us/step - loss: 0.5307 - accuracy: 0.7409
Epoch 169/250
804/804 [==============================] - 1s 748us/step - loss: 0.5305 - accuracy: 0.7410
Epoch 170/250
804/804 [==============================] - 1s 753us/step - loss: 0.5311 - accuracy: 0.7401
Epoch 171/250
804/804 [==============================] - 1s 745us/step - loss: 0.5309 - accuracy: 0.7415
Epoch 172/250
804/804 [==============================] - 1s 757us/step - loss: 0.5313 - accuracy: 0.7412
Epoch 173/250
804/804 [==============================] - 1s 742us/step - loss: 0.5313 - accuracy: 0.7409
Epoch 174/250
804/804 [==============================] - 1s 766us/step - loss: 0.5308 - accuracy: 0.7411
Epoch 175/250
804/804 [==============================] - 1s 765us/step - loss: 0.5307 - accuracy: 0.7411
Epoch 176/250
804/804 [==============================] - 1s 759us/step - loss: 0.5305 - accuracy: 0.7417
Epoch 177/250
804/804 [==============================] - 1s 751us/step - loss: 0.5306 - accuracy: 0.7416
Epoch 178/250
804/804 [==============================] - 1s 748us/step - loss: 0.5310 - accuracy: 0.7418
Epoch 179/250
804/804 [==============================] - 1s 760us/step - loss: 0.5306 - accuracy: 0.7418
Epoch 180/250
804/804 [==============================] - 1s 751us/step - loss: 0.5306 - accuracy: 0.7409
Epoch 181/250
804/804 [==============================] - 1s 744us/step - loss: 0.5305 - accuracy: 0.7418
Epoch 182/250
804/804 [==============================] - 1s 746us/step - loss: 0.5305 - accuracy: 0.7416
Epoch 183/250
804/804 [==============================] - 1s 755us/step - loss: 0.5305 - accuracy: 0.7418
Epoch 184/250
804/804 [==============================] - 1s 748us/step - loss: 0.5306 - accuracy: 0.7418
Epoch 185/250
804/804 [==============================] - 1s 759us/step - loss: 0.5309 - accuracy: 0.7415
Epoch 186/250
804/804 [==============================] - 1s 746us/step - loss: 0.5304 - accuracy: 0.7415
Epoch 187/250
804/804 [==============================] - 1s 748us/step - loss: 0.5307 - accuracy: 0.7414
Epoch 188/250
804/804 [==============================] - 1s 750us/step - loss: 0.5305 - accuracy: 0.7411
Epoch 189/250
804/804 [==============================] - 1s 750us/step - loss: 0.5303 - accuracy: 0.7414
Epoch 190/250
804/804 [==============================] - 1s 757us/step - loss: 0.5309 - accuracy: 0.7417
Epoch 191/250
804/804 [==============================] - 1s 761us/step - loss: 0.5313 - accuracy: 0.7414
Epoch 192/250

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5828 - accuracy: 0.7277 - 232ms/epoch - 866us/step
Loss: 0.5827525854110718, Accuracy: 0.7276967763900757

In [17]:
# Export our model to HDF5 file
model_file= "Output/AlphabetSoupCharity_Optimization1.h5"
nn.save(model_file)
print(f"Model saved to {model_file}")

Model saved to Output/AlphabetSoupCharity_Optimization1.h5

c:\Users\eurib\anaconda3\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(